# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types: [opened, reopened, synchronize]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp
    environment: devhub

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: 'Checkout source code'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Runs a single command using the runners shell
    # - name: Login to DevHub
    #   shell: bash
    #   run: |
    #     echo  ${{ secrets.SFDX_AUTH_DEVHUB }} > ./authurlfile
    #     sf org login sfdx-url --sfdx-url-file authurlfile --set-default-dev-hub --alias=devhub
    
    # - name: Check login
    #   run: |
    #     sf org list
    # - name: Scanner
    #   run: |
    #     sf scanner run --format sarif --target './**/*.cls' --category "Design,Best Practices,Performance" --outfile 'apexScanResults.sarif'
    # - name: Upload SARIF file
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: apexScanResults.sarif
    - name: Login to DevHub in docker
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/flxbl-io/sfp
        options: -v ${{ github.workspace }}:/work
        run: |
          cd work
          echo  ${{ secrets.SFDX_AUTH_DEVHUB }} > ./authurlfile
          sf org login sfdx-url --sfdx-url-file authurlfile --set-default-dev-hub --alias=devhub
          sf org list
          ls -la

    - name: check volume
      run: |
        ls -la

    - name: Check login in docker
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/flxbl-io/sfp
        options: -v ${{ github.workspace }}:/work
        run: |
          cd work
          sf org list
